version: '3'

services:
  php:
    image: laravel-app-php
    container_name: laravel-app-php
    volumes:
      - ./path_to_your_laravel_project:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    container_name: laravel-app-nginx
    ports:
      - "8082:8082"
    volumes:
      - ./path_to_your_laravel_project:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

